services:
  # Frontend Service (assuming it's on Netlify, so this is for context)
  # You do not need to deploy the frontend to Render if it's on Netlify.

  # Backend Service (for Render)
  - type: web
    name: gso-backend
    env: docker # IMPORTANT: Use the Docker environment
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO # Replace with your actual GitHub repo URL
    region: singapore # Or your preferred region
    plan: free # Or your preferred plan
    # The following path should point to your backend's Dockerfile
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /api/health # Recommended: Add a health check route to your server.js
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: gso-mongodb # IMPORTANT: Use the name of your MongoDB service on Render
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # Let Render generate a secure secret
      - key: PORTAL_API_URL
        value: https://lgu-helpdesk-copy.onrender.com/api
      - key: NODE_ENV
        value: production